### ISSUE TITLE
ZodUnion type as discriminator?

### ISSUE THREAD

**Issue by dplantera** [teunmooij/zod-discriminated-union#4]
Hey,

first of all, thx for the initiative for supporting various discriminator property types! 

I as well have an usecase for nested discriminatedUnions where a related schema may have multiple discriminator string values.

Currently we are expressing those values as unions but we may could migrate to enums since this seems to be supported out of the box. 

Yet, I wonder if this lib could support unions as discriminator property. What do you think? I am happy to give it a shot.

This is how the types may look like: 

```ts
type A = { d: 'a' | 'aa'; val: string }
type B = { d: 'b' ; val: number }
type Union = A | B
```
And this would be something we need to express with zod:

```ts
const dUnion = z.discriminstedUnion( 'd' , [
 z.object({ d: z.union([ z.literal('a'), z.literal('baa') ]), val: z.string() },
 z.object({ d: z.literal('b'), val: z.number() }),
])
```

**Comment by dplantera** [comment]
nvm works like a charme with z.union for discriminator properties.

Thanks for sharing!

**Comment by teunmooij** [comment]
Sorry I missed your original message. I think in your case you can use `z.enum(['a', 'aa'])`.

**Comment by dplantera** [comment]
np - I just want to add that z.union seemed to work on type level but actually doesn't. 
However using z.enum would fix it.

**Comment by stdedos** [comment]
Would you @teunmooij mind "emphasizing" that somewhere? :confused:

It was not immediately apparent to me that:

```ts
    type: z.union([z.literal('aaa'), z.literal('bbb')]),
```

`===`

```ts
    type: z.enum(['aaa', 'bbb']),
```

(I'd prefer a targeted message during the `throw new Error` ordeal, but - even just at your front page's README.md would be fine by me)
